quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:vehicle}
quarkus.datasource.password=${DB_PASSWORD:vehicle}
quarkus.datasource.jdbc.url=${JDBC_URL:jdbc:postgresql://localhost:5432/vehicle}

#quarkus.rest-client.fipe-api.url=${FIPE_API_BASE_URL:https://parallelum.com.br/fipe/api/v1}
quarkus.rest-client.fipe-api.url=${FIPE_API_BASE_URL:http://localhost:8090}
quarkus.rest-client.fipe-api.connect-timeout=${FIPE_API_CONNECT_TIMEOUT:10000}
quarkus.rest-client.fipe-api.read-timeout=${FIPE_API_READ_TIMEOUT:60000}

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:${RABBITMQ_USER:vehicle}}
rabbitmq-password=${RABBITMQ_PASSWORD:${RABBITMQ_PASS:vehicle}}

mp.messaging.incoming.brands-in.connector=smallrye-rabbitmq
mp.messaging.incoming.brands-in.exchange.name=vehicle-brands
mp.messaging.incoming.brands-in.exchange.type=fanout
mp.messaging.incoming.brands-in.exchange.declare=true
mp.messaging.incoming.brands-in.queue.name=vehicle-brands-api2
mp.messaging.incoming.brands-in.queue.declare=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:vehicletest2;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create
# smallrye-in-memory: dependência smallrye-reactive-messaging-in-memory (test) no pom
%test.mp.messaging.incoming.brands-in.connector=smallrye-in-memory
